// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNlyKN9kcoDw-Eo2CWzHLgXubOKWErLM',
    appId: '1:1060542671824:web:913a55493a5741207ce7d5',
    messagingSenderId: '1060542671824',
    projectId: 'eos-chatting-1fa9b',
    authDomain: 'eos-chatting-1fa9b.firebaseapp.com',
    storageBucket: 'eos-chatting-1fa9b.appspot.com',
    measurementId: 'G-6BBYMGJ3R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAe48OKVSGIGymTQg9OmCetoAQoO7DWkQ',
    appId: '1:1060542671824:android:5b943e2bac006ba17ce7d5',
    messagingSenderId: '1060542671824',
    projectId: 'eos-chatting-1fa9b',
    storageBucket: 'eos-chatting-1fa9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7EE0cG3W5j2N-Dk4LSOl7ww5vRjBS-Kk',
    appId: '1:1060542671824:ios:2a828c6308715ae57ce7d5',
    messagingSenderId: '1060542671824',
    projectId: 'eos-chatting-1fa9b',
    storageBucket: 'eos-chatting-1fa9b.appspot.com',
    iosClientId: '1060542671824-q68b68m48letb5106qa0pp9pb830lhmh.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7EE0cG3W5j2N-Dk4LSOl7ww5vRjBS-Kk',
    appId: '1:1060542671824:ios:2a828c6308715ae57ce7d5',
    messagingSenderId: '1060542671824',
    projectId: 'eos-chatting-1fa9b',
    storageBucket: 'eos-chatting-1fa9b.appspot.com',
    iosClientId: '1060542671824-q68b68m48letb5106qa0pp9pb830lhmh.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
